import { config } from "dotenv";

config();

export const {
  PORT,
  DB_USER,
  DB_HOST,
  DB_PASSWORD,
  DB_NAME,
  SECRET_JWT_KEY,
  SECRET_JWT_REFRESH_KEY,
  ENCRYPTION_KEY,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_TYPE,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  FIREBASE_CLIENT_X509_CERT_URL,
  FIREBASE_UNIVERSE_DOMAIN,
} = process.env;
